### ISSUE TITLE
Can't build on Arch Linux 

### ISSUE THREAD

**Issue by 1fxe** [chromiumembedded/java-cef#475]
**Describe the bug**
Seems to be an issue with the gsutil version used, python2 has been removed and the library six used to managed compatability is not being imported properly

```sh
/clang-format, skipping. [Err: Traceback (most recent call last):
  File "/home/filip/Documents/git/java-cef/tools/buildtools/external_bin/gsutil/gsutil_4.68/gsutil/gsutil", line 21, in <module>
    gsutil.RunMain()
  File "/home/filip/Documents/git/java-cef/tools/buildtools/external_bin/gsutil/gsutil_4.68/gsutil/gsutil.py", line 121, in RunMain
    import gslib.__main__
  File "/home/filip/Documents/git/java-cef/tools/buildtools/external_bin/gsutil/gsutil_4.68/gsutil/gslib/__main__.py", line 36, in <module>
    from six.moves import configparser
ModuleNotFoundError: No module named 'six.moves'
]
Downloading 1 files took 0.082395 second(s)
```

**To Reproduce**
1. Follow instructions here https://bitbucket.org/chromiumembedded/java-cef/wiki/BranchesAndBuilding.md`

**Expected behavior**
Should build make file, 

**Screenshots**

**Versions (please complete the following information):**
 - Arch Linux 

**Additional context**
Upgrading to 5.30 (the latest version) allows me to compile 

https://github.com/chromiumembedded/java-cef/blob/7a13412adc5dd6de4617d948940da398ec36f47e/tools/buildtools/gsutil.py#L37 
Change here to `5.30`

**Comment by DRV2539** [comment]
I was getting this same issue for Windows, I downgraded my Python version from 3.12 to 3.7 and it worked for me.

**Comment by magreenblatt** [comment]
We can update the library version. Chromium is using Python 3.11 currently.

**Comment by magreenblatt** [comment]
The current version (4.68) appears to work with Python 3.9.6 (Mac default).
